### ISSUE TITLE
Runtime exception with Phaser v3.60.0-beta.17

### ISSUE THREAD

**Issue by vpmedia** [jjcapellan/phaser3-bitmapfont-factory#1]
When I try to use the library I get an exception:

`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.width')`

bmff.ems.js:14602

```
const bmff = new BMFFactory(this, () => {
 // on complete handler
});
bmff.make("key1", "Arial", "0123456789", { fontSize: "24px", color: "#FFFFFF" }, false);
bmff.exec();
```

**Comment by jjcapellan** [comment]
Thanks for the info !!. 
I have reviewed the Phaser changelog and indeed there are some changes that break the functionality of the library. I will check it out.

**Comment by jjcapellan** [comment]
New version v1.1.1 should work correctly. I have tested it with Phaser 3.55.2 and Phaser 3.60.0-beta18.  
I will leave this issue open for a few days in case you get any errors.

**Comment by vpmedia** [comment]
@jjcapellan Super, thanks!
